In [3]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('irish_rent_full.csv')
df.head() # here e have to predict the rent_euro

   rent_euro  year  half half_year  time_period  county  ...       property_type      bedrooms bedrooms_num is_dublin is_city  is_county_aggregate
0     835.90  2020     1    2020H1            1  Carlow  ...  All property types  All bedrooms          NaN     False   False                 True
1     860.74  2020     1    2020H1            1  Carlow  ...  All property types  All bedrooms          NaN     False   False                False
2     910.91  2020     1    2020H1            1  Carlow  ...  All property types  All bedrooms          NaN     False   False                False
3     812.14  2020     1    2020H1            1  Carlow  ...  All property types  All bedrooms          NaN     False   False                False
4     666.31  2020     1    2020H1            1   Cavan  ...  All property types  All bedrooms          NaN     False   False                 True

[5 rows x 15 columns]

In [5]:
df.describe()

          rent_euro          year          half   time_period  bedrooms_num
count  50208.000000  50208.000000  50208.000000  50208.000000  37869.000000
mean    1306.508984   2021.950506      1.479366      5.380378      2.123901
std      528.333082      1.559695      0.499579      3.105849      0.782008
min      401.580000   2020.000000      1.000000      1.000000      1.000000
25%      888.455000   2021.000000      1.000000      3.000000      1.500000
50%     1200.435000   2022.000000      1.000000      5.000000      2.000000
75%     1649.057500   2023.000000      2.000000      8.000000      2.000000
max     5372.870000   2025.000000      2.000000     11.000000      4.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50208 entries, 0 to 50207
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rent_euro            50208 non-null  float64
 1   year                 50208 non-null  int64
 2   half                 50208 non-null  int64
 3   half_year            50208 non-null  object
 4   time_period          50208 non-null  int64
 5   county               50208 non-null  object
 6   province             50208 non-null  object
 7   area                 50208 non-null  object
 8   location             50208 non-null  object
 9   property_type        50208 non-null  object
 10  bedrooms             50208 non-null  object
 11  bedrooms_num         37869 non-null  float64
 12  is_dublin            50208 non-null  bool
 13  is_city              50208 non-null  bool
 14  is_county_aggregate  50208 non-null  bool
dtypes: bool(3), float64(2), int64(3), object(7)
memory usage: 4.7+ MB

In [7]:
df['bedrooms_num'].fillna(df['bedrooms_num'].mean(),inplace=True)#let's perform one hot encoding

C:\Users\tanis\AppData\Local\Temp\ipykernel_15140\2336376403.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bedrooms_num'].fillna(df['bedrooms_num'].mean(),inplace=True)#let's perform one hot encoding

In [8]:
df['Period'] = df['half_year'].apply(lambda x:int(x[:4] + x[5]))
df.head()

   rent_euro  year  half half_year  time_period  county  ...      bedrooms bedrooms_num is_dublin is_city is_county_aggregate  Period
0     835.90  2020     1    2020H1            1  Carlow  ...  All bedrooms     2.123901     False   False                True   20201
1     860.74  2020     1    2020H1            1  Carlow  ...  All bedrooms     2.123901     False   False               False   20201
2     910.91  2020     1    2020H1            1  Carlow  ...  All bedrooms     2.123901     False   False               False   20201
3     812.14  2020     1    2020H1            1  Carlow  ...  All bedrooms     2.123901     False   False               False   20201
4     666.31  2020     1    2020H1            1   Cavan  ...  All bedrooms     2.123901     False   False                True   20201

[5 rows x 16 columns]

In [9]:
df.drop(columns=['half_year'],inplace=True)

In [10]:
X = df.drop(columns=['rent_euro'],axis=1)
y = df['rent_euro']

In [11]:
X

       year  half  time_period    county  province           area  ...       bedrooms bedrooms_num is_dublin  is_city  is_county_aggregate  Period
0      2020     1            1    Carlow  Leinster         Carlow  ...   All bedrooms     2.123901     False    False                 True   20201
1      2020     1            1    Carlow  Leinster    Carlow Town  ...   All bedrooms     2.123901     False    False                False   20201
2      2020     1            1    Carlow  Leinster  Graiguecullen  ...   All bedrooms     2.123901     False    False                False   20201
3      2020     1            1    Carlow  Leinster         Tullow  ...   All bedrooms     2.123901     False    False                False   20201
4      2020     1            1     Cavan    Ulster          Cavan  ...   All bedrooms     2.123901     False    False                 True   20201
...     ...   ...          ...       ...       ...            ...  ...            ...          ...       ...      ...                  ...     ...
50203  2025     1           11  Limerick   Munster       Limerick  ...  Four plus bed     4.000000     False    False                 True   20251
50204  2025     1           11  Limerick   Munster  Limerick City  ...  Four plus bed     4.000000     False     True                False   20251
50205  2025     1           11      Cork   Munster           Cork  ...  Four plus bed     4.000000     False    False                 True   20251
50206  2025     1           11    Dublin  Leinster         Dublin  ...  Four plus bed     4.000000      True     True                 True   20251
50207  2025     1           11    Galway  Connacht         Galway  ...  Four plus bed     4.000000     False    False                 True   20251

[50208 rows x 14 columns]

In [12]:
X_one_encode = pd.get_dummies(X,columns=['county','province', 'area', 'location', 'property_type', 'bedrooms','Period'],drop_first=True)
X_one_encode

       year  half  time_period  bedrooms_num  is_dublin  is_city  ...  Period_20222  Period_20231  Period_20232  Period_20241  Period_20242  Period_20251
0      2020     1            1      2.123901      False    False  ...         False         False         False         False         False         False
1      2020     1            1      2.123901      False    False  ...         False         False         False         False         False         False
2      2020     1            1      2.123901      False    False  ...         False         False         False         False         False         False
3      2020     1            1      2.123901      False    False  ...         False         False         False         False         False         False
4      2020     1            1      2.123901      False    False  ...         False         False         False         False         False         False
...     ...   ...          ...           ...        ...      ...  ...           ...           ...           ...           ...           ...           ...
50203  2025     1           11      4.000000      False    False  ...         False         False         False         False         False          True
50204  2025     1           11      4.000000      False     True  ...         False         False         False         False         False          True
50205  2025     1           11      4.000000      False    False  ...         False         False         False         False         False          True
50206  2025     1           11      4.000000       True     True  ...         False         False         False         False         False          True
50207  2025     1           11      4.000000      False    False  ...         False         False         False         False         False          True

[50208 rows x 873 columns]

In [13]:
df.columns

Index(['rent_euro', 'year', 'half', 'time_period', 'county', 'province',
       'area', 'location', 'property_type', 'bedrooms', 'bedrooms_num',
       'is_dublin', 'is_city', 'is_county_aggregate', 'Period'],
      dtype='object')

In [14]:
X_one_encode = X_one_encode.astype(int)
X_one_encode

       year  half  time_period  bedrooms_num  is_dublin  is_city  ...  Period_20222  Period_20231  Period_20232  Period_20241  Period_20242  Period_20251
0      2020     1            1             2          0        0  ...             0             0             0             0             0             0
1      2020     1            1             2          0        0  ...             0             0             0             0             0             0
2      2020     1            1             2          0        0  ...             0             0             0             0             0             0
3      2020     1            1             2          0        0  ...             0             0             0             0             0             0
4      2020     1            1             2          0        0  ...             0             0             0             0             0             0
...     ...   ...          ...           ...        ...      ...  ...           ...           ...           ...           ...           ...           ...
50203  2025     1           11             4          0        0  ...             0             0             0             0             0             1
50204  2025     1           11             4          0        1  ...             0             0             0             0             0             1
50205  2025     1           11             4          0        0  ...             0             0             0             0             0             1
50206  2025     1           11             4          1        1  ...             0             0             0             0             0             1
50207  2025     1           11             4          0        0  ...             0             0             0             0             0             1

[50208 rows x 873 columns]

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [18]:
# Target variable
y = df['rent_euro']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_one_encode,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
scaler = StandardScaler()#It is necessary for knn,decisontree and svm.
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
#here only linearRegression and Randomforest can be performed as we have to predict continous varible that is rent

In [23]:
from sklearn.linear_model import LinearRegression

# Initialize model
lr = LinearRegression()

# Train model
lr.fit(X_train, y_train)

LinearRegression()

In [24]:
y_train_pred = lr.predict(X_train)
y_test_pred = lr.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Training metrics
print("Training Performance")
print("MAE:", mean_absolute_error(y_train, y_train_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_train_pred)))
print("R2 Score:", r2_score(y_train, y_train_pred))

print("\nTesting Performance")
print("MAE:", mean_absolute_error(y_test, y_test_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_test_pred)))
print("R2 Score:", r2_score(y_test, y_test_pred))

Training Performance
MAE: 98.24473845674251
RMSE: 156.37889764181344
R2 Score: 0.9126783705824342

Testing Performance
MAE: 99.76617805869745
RMSE: 155.58387905204177
R2 Score: 0.9121182217947397

In [30]:
import joblib

joblib.dump(lr, 'model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X.columns.tolist(), 'columns.pkl')

['columns.pkl']

In [31]:
import joblib

cols = joblib.load("columns.pkl")
print(cols[:15])

['year', 'half', 'time_period', 'county', 'province', 'area', 'location', 'property_type', 'bedrooms', 'bedrooms_num', 'is_dublin', 'is_city', 'is_county_aggregate', 'Period']